### ISSUE TITLE
Error when using lmcache_vllm.vllm.LLM() with tensor parallelism

### ISSUE THREAD

**Issue by CriusT** [LMCache/lmcache-vllm#29]
It seems that the tensor parallel support cannot work with `vllm.LLM()`. (After updating to https://github.com/LMCache/lmcache-vllm/commit/d4b647213b758f87f17841811858bfb53ae09bba, I can run the `test_lmcache_local_distributed` test normally.). When I run the code, it encounters the error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/miniconda3/envs/lmcache/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/miniconda3/envs/lmcache/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/miniconda3/envs/lmcache/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cpu001/LMCache/tby-test/run_lmcache_vllm.py", line 27, in <module>
    llm = vllm.LLM(model=model_path, tensor_parallel_size=2, gpu_memory_utilization=0.6)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 178, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 550, in from_engine_args
    engine = cls(
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 317, in __init__
    self.model_executor = executor_class(
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 89, in _init_executor
    worker = ProcessWorkerWrapper(
  File "/home/miniconda3/envs/lmcache/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 162, in __init__
    self.process.start()
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/miniconda3/envs/lmcache/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
ERROR 10-28 02:27:46 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 12137 died, exit code: 1
INFO 10-28 02:27:46 multiproc_worker_utils.py:123] Killing local vLLM worker processes
```

The test code is here (if I don't set the `os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"`, the cuda initialization error will occur as in https://github.com/LMCache/lmcache-vllm/pull/22):
```
from lmcache_vllm import vllm
"""
and you are good to go!
"""
import os

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]

os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
sampling_params = vllm.SamplingParams(temperature=0.8, top_p=0.95)
model_path = "/home/models/huggingface.co/Qwen/Qwen2.5-7B-Instruct"

llm = vllm.LLM(model=model_path, tensor_parallel_size=2, gpu_memory_utilization=0.6)
outputs = llm.generate(prompts, sampling_params)
```

**Comment by ApostaC** [comment]
Hi @CriusT , thanks for your question! Can you maybe try wrapping the main script with `if __name__ == "__main__"`? Here's an example:
```python
from lmcache_vllm import vllm, close_lmcache_engine
"""
and you are good to go!
"""
import os

os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"

if __name__ == "__main__":
    prompts = [
        "Hello, my name is",
        "The president of the United States is",
        "The capital of France is",
        "The future of AI is",
    ]

    sampling_params = vllm.SamplingParams(temperature=0.8, top_p=0.95)
    model_path = "/home/models/huggingface.co/Qwen/Qwen2.5-7B-Instruct"

    llm = vllm.LLM(model=model_path, tensor_parallel_size=2, gpu_memory_utilization=0.6)
    outputs = llm.generate(prompts, sampling_params)

    close_lmcache_engine()

```

I've tested locally with `model_path = "mistralai/Mistral-7B-Instruct-v0.2"` and it should work. Let me know if it doesn't work for Qwen models.

**Comment by CriusT** [comment]
It works. Thanks a lot!
